import React from "react";
import Head from "next/head";
import fs from "fs";
import matter from "gray-matter";
import { Header } from "../../components/global/Header";
import { Footer } from "../../components/global/Footer";
import Link from "next/link";

export default function Posts(props) {
    const {posts} = props;
    return(
        <>
            <Head>
                <title>Posts | Nikita Gorshkov</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Header />
            <div className="flex flex-col h-screen">
                <div className="h-[76px]"></div>
                <div className="w-[60%] mx-[20%] mt-12">
                    <h1 className="text-white font-bold text-5xl mb-5">Posts</h1>
                    <ul className="flex flex-col gap-y-7 pb-10">
                        {posts.map((post, index) => (
                            <Link href={`/posts/${post.slug}`} key={index}>
                                <li className="flex flex-col gap-y-1 p-3 rounded-xl border-2 border-gray-400 hover:bg-gray-800 ease-in-out transition duration-300">
                                    <div className="flex flex-row justify-between items-center">
                                        <h2 className="text-white text-xl font-semibold">{post.data.title}</h2>
                                        <div>
                                            {post.data.tags.map((tag, tagIndex) => (
                                                <span key={tag} className="text-[#5187df] hover:text-[#5d9bff] ease-in-out transition duration-300">
                                                    <Link href={`/posts?tag=${tag}`}>{tag}</Link>
                                                    {tagIndex!=post.data.tags.length-1 && <span className="mx-1">•</span>}
                                                </span>
                                            ))}
                                        </div>
                                    </div>
                                    <p className="text-gray-200 text-lg">{new Date(post.data.date).toLocaleString("en-US", 
                                    {
                                        year: "numeric",
                                        month: "long",
                                        day: "numeric",
                                    })}</p>
                                    <p className="text-white text-lg">{post.data.description}</p>
                                </li>
                            </Link>
                        ))}
                    </ul>
                </div>
                <Footer />
            </div>
        </>
    )
}

export async function getStaticProps() {
    const files = fs.readdirSync(`${process.cwd()}/posts`, "utf-8");
    const posts = files.map((post) => {
        const slug = post.replace(".md", "");
        const fileContent = fs.readFileSync(`${process.cwd()}/posts/${post}`, "utf-8");
        const parsedContent = matter(fileContent);
        const {data} = parsedContent;
        return {slug, data};
    });
    posts.sort((a, b) => {
        return new Date(b.date) - new Date(a.date);
    });
    return {
        props:{
            posts
        }
    }
}