import React from "react";
import Head from "next/head";
import { Header } from "../components/global/Header";
import { Footer } from "../components/global/Footer";
import { Form } from "../components/contact/Form";

export default function Projects() {
    return(
        <>
            <Head>
                <title>Contact Me | Nikita Gorshkov</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className="flex flex-col min-h-screen">
                <Header />
                <div className="flex justify-center items-center grow">
                    <Form />
                </div>
                <Footer />
            </main>
        </>
    )
}