import React from "react";
import Head from "next/head";
import { Header } from "../components/global/Header";
import { Footer } from "../components/global/Footer";
import { Form } from "../components/contact/Form";

export default function Projects() {
    return(
        <>
            <Head>
                <title>Contact Me | Nikita Gorshkov</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Header />
            <div className="flex flex-col h-screen">
                <div className="h-[76px]"></div>
                <div className="flex justify-center items-center flex-auto">
                    <Form />
                </div>
                <Footer />
            </div>
        </>
    )
}