import React from "react";
import Head from "next/head";
import { Header } from "../components/global/Header";
import { Footer } from "../components/global/Footer";

export default function Projects() {
    return(
        <>
            <Head>
                <title>Posts</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Header />
            <div className="flex flex-col h-screen">
                <div className="h-[76px]"></div>
                <div className="flex w-[60%] px-[20%] flex-auto pt-10">
                    <p className="text-white font-bold text-5xl">Posts</p>
                    
                </div>
                <Footer />
            </div>
        </>
    )
}