import React from "react";
import Head from "next/head";
import { Header } from "../components/global/Header";
import { Footer } from "../components/global/Footer";
import ProjectCard from "../components/projects/ProjectCard";
import projectList from "../components/projects/projectList";

export default function Projects() {
    return(
        <>
            <Head>
                <title>Projects | Nikita Gorshkov</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className="flex flex-col min-h-screen">
                <Header />
                <div className="flex flex-col w-[60%] mx-[20%] my-12 grow">
                    <h1 className="text-white font-bold text-5xl mb-5">Projects</h1>
                    <div className="grid grid-cols-2 gap-4">
                        {projectList.map((project, key) => (
                            <ProjectCard 
                                key={key}
                                name={project.name}
                                link={project.link}
                                github={project.github}
                                startColor={project.startColor}
                                endColor={project.endColor}
                                description={project.description}
                            />
                        ))}
                    </div>
                </div>
                <Footer />
            </main>
        </>
    )
}