import React from "react";
import Head from "next/head";
import Link from "next/link";
import { Header } from "../components/global/Header";
import { Footer } from "../components/global/Footer";

export default function Tags() {
    return(
        <>
            <Head>
                <title>Tags | Nikita Gorshkov</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className="flex flex-col min-h-screen">
                <Header />
                <Footer />
            </main>
        </>
    )
}