import React from "react";
import Head from "next/head";
import Link from "next/link";
import { Header } from "../../components/global/Header";
import { Footer } from "../../components/global/Footer";

export default function Tags() {
    return(
        <>
            <Head>
                <title>Tags | Nikita Gorshkov</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className="flex flex-col min-h-screen">
                <Header />
                
                <Footer />
            </main>
        </>
    )
}

export async function getStaticProps() {
    const files = fs.readdirSync(`${process.cwd()}/posts`, "utf-8");
    const posts = files.map((post) => {
        const slug = post.replace(".md", "");
        const fileContent = fs.readFileSync(`${process.cwd()}/posts/${post}`, "utf-8");
        const parsedContent = matter(fileContent);
        const {data} = parsedContent;
        return {slug, data};
    });
    posts.sort((a, b) => {
        return new Date(b.data.date) - new Date(a.data.date);
    });
    return {
        props:{
            posts
        }
    }
}

export const getTags = () => {
    const posts = getStaticProps();
    let tags = [];
    posts.forEach((post) => {
        if (post?.data?.tags) {
            tags = [...tags, ...post.data.tags];
        }
    })
    return tags;
}

export const getUniqueTags = () => {
    const tags = getTags();
    return Array.from(new Set(tags));
  };